-- Enable RLS on all public tables to fix Supabase security warnings
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MonthlyBudget" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Leave" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Department" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AutomationRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OperatingDay" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShiftTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserBaseRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Shift" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SchedulePublish" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Constraint" ENABLE ROW LEVEL SECURITY;
